collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.4204527919646353
color:
  saturation: 0.2331318692304194
  brandStrength: 0.6395140727981925
  rhythmicContrast: 0.359567730454728
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  lightness: 0.5009551523253322
layout_spectrum: 1
name: TWSI
